project_id = "ahhcbwbvueimezmtftte"

[functions.send-otp]
verify_jwt = false

[functions.mchango-crud]
verify_jwt = false

[functions.chama-crud]
verify_jwt = false

[functions.chama-invite]
verify_jwt = true

[functions.chama-join]
verify_jwt = true

[functions.contributions-crud]
verify_jwt = true

[functions.transactions-crud]
verify_jwt = true

[functions.mpesa-stk-push]
verify_jwt = true

[functions.mpesa-callback]
verify_jwt = false